### ISSUE TITLE
ArrayIndexOutOfBoundsException & java.lang.NullPointerException

### ISSUE THREAD

**Issue by SpongebBob** [kaz-Anova/StackNet#10]
I encountered this problem with my own features in the Kaggle of Quora、

> Exception in thread "Thread-6" java.lang.ArrayIndexOutOfBoundsException: 750
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3002)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3038)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3042)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3042)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3038)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3038)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3038)
	at ml.Tree.DecisionTreeRegressor.expand_node(DecisionTreeRegressor.java:3038)
	at ml.Tree.DecisionTreeRegressor.fit(DecisionTreeRegressor.java:2382)
	at ml.Tree.DecisionTreeRegressor.run(DecisionTreeRegressor.java:483)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-3" java.lang.NullPointerException
	at ml.Tree.DecisionTreeRegressor.isfitted(DecisionTreeRegressor.java:3275)
	at ml.Tree.scoringhelperv2.<init>(scoringhelperv2.java:107)
	at ml.Tree.RandomForestRegressor.predict2d(RandomForestRegressor.java:744)
	at ml.Tree.GradientBoostingForestClassifier.fit(GradientBoostingForestClassifier.java:2353)
	at ml.Tree.GradientBoostingForestClassifier.run(GradientBoostingForestClassifier.java:382)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-1112" java.lang.ArrayIndexOutOfBoundsException: 983
	at ml.Tree.DecisionTreeClassifier.expand_node(DecisionTreeClassifier.java:3185)
	at ml.Tree.DecisionTreeClassifier.expand_node(DecisionTreeClassifier.java:3225)
	at ml.Tree.DecisionTreeClassifier.expand_node(DecisionTreeClassifier.java:3225)
	at ml.Tree.DecisionTreeClassifier.expand_node(DecisionTreeClassifier.java:3221)
	at ml.Tree.DecisionTreeClassifier.expand_node(DecisionTreeClassifier.java:3225)
	at ml.Tree.DecisionTreeClassifier.fit(DecisionTreeClassifier.java:2576)
	at ml.Tree.DecisionTreeClassifier.run(DecisionTreeClassifier.java:537)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-1137" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-1617" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-1642" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2075" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2284" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2365" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2382" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2463" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2608" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2721" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2802" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2883" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-2996" java.lang.ArrayIndexOutOfBoundsException
 logloss : 0.257352525104832
 logloss : 2.4462523363834303
Exception in thread "main" java.lang.NullPointerException
	at ml.Tree.DecisionTreeClassifier.isfitted(DecisionTreeClassifier.java:3458)
	at ml.Tree.scoringhelpercatv2.<init>(scoringhelpercatv2.java:107)
	at ml.Tree.RandomForestClassifier.predict_proba(RandomForestClassifier.java:795)
	at ml.stacknet.StackNetClassifier.fit(StackNetClassifier.java:3532)
	at stacknetrun.runstacknet.main(runstacknet.java:437)

I am sure that there is no zero like 0.000000 in the sparse file and all the data is  in order。
/(ㄒoㄒ)/~~

**Comment by xiaofeifei1800** [comment]
Same issue

**Comment by xiaofeifei1800** [comment]
@SpongebBob Does it generate querry_pred.csv file? I can't find it.

**Comment by kaz-Anova** [comment]
Could you care to re-test with the new version?

**Comment by xiaofeifei1800** [comment]
I will try today and let you know

**Comment by SpongebBob** [comment]
@kaz-Anova  I add round=30 to the tree based model, the bug is gone!

**Comment by SpongebBob** [comment]
@xiaofeifei1800 If you use  tree based model, maybe you should try add param round. It worked for me.
