### ISSUE TITLE
Error- no changes made to Zillo Example

### ISSUE THREAD

**Issue by rahasayantan** [kaz-Anova/StackNet#38]
I tried using the example as is except changing the Bag and Bin counts.. I get the following error.
I have ubuntu 14.04 (trusty)
Java 1.8

Command and error
StackNet$ java -Xmx12048m -jar StackNet.jar train task=regression sparse=true has_head=false output_name=datasettwo model=model2 pred_file=pred2.csv train_file=dataset2_train.txt test_file=dataset2_test.txt test_target=false params=dataset2_params.txt verbose=true threads=1 metric=mae stackdata=false seed=1 folds=5 bins=2
parameter name : task value :  regression
parameter name : sparse value :  true
parameter name : has_head value :  false
parameter name : output_name value :  datasettwo
parameter name : model value :  model2
parameter name : pred_file value :  pred2.csv
parameter name : train_file value :  dataset2_train.txt
parameter name : test_file value :  dataset2_test.txt
parameter name : test_target value :  false
parameter name : params value :  dataset2_params.txt
parameter name : verbose value :  true
parameter name : threads value :  1
parameter name : metric value :  mae
parameter name : stackdata value :  false
parameter name : seed value :  1
parameter name : folds value :  5
parameter name : bins value :  2
[4793209, 88528]
 Loaded File: dataset2_train.txt
 Total rows in the file: 88528
 Total columns in the file: undetrmined-Sparse
 Number of elements : 4793209
 The filedataset2_train.txt was loaded successfully with :
 Rows : 88528
 Columns (excluding target) : 1
 Delimeter was  :  
Loaded sparse train data with 88528 and columns 58
 loaded data in : 10.403000
 Binning parameters 
[0.005, <=0.005]
[0.4187, <=0.4187]
 Level: 1 dimensionality: 12
 Starting cross validation 
Fitting model : 0
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalStateException:  Tree is not fitted
	at ml.Bagging.scoringhelperbagv2.<init>(scoringhelperbagv2.java:109)
	at ml.Bagging.BaggingRegressor.predict2d(BaggingRegressor.java:669)
	at ml.Bagging.BaggingRegressor.predict_proba(BaggingRegressor.java:1875)
	at ml.stacknet.StackNetRegressor.fit(StackNetRegressor.java:3065)
	at stacknetrun.runstacknet.main(runstacknet.java:522)
	... 5 more

**Comment by goldentom42** [comment]
Hi rahasayantan, 
It looks like you have a problem with the 1st regressor, which is LightGBM.
Did you make it executable as explained [here](https://github.com/kaz-Anova/StackNet#install-lightgbm) ?

**Comment by kaz-Anova** [comment]
@rahasayantan 

Also see [my response here](https://github.com/kaz-Anova/StackNet/issues/28)

**Comment by rahasayantan** [comment]
I understand the problem is very basic. I use Python 2.7.. And the installables shipped are for Python 3.0+.. I need to change the lib and executable to reflect my version of python...

I am closing this issue. Thanks for your help and support.. This is a fantastic tool..
