### ISSUE TITLE
Issue when calling XGBOOSTRegressor

### ISSUE THREAD

**Issue by woaipaopao** [kaz-Anova/StackNet#50]
Hi @kaz-Anova,

Encounter the following issue when calling XGBRegressor during prediction stage for Zillow Competition and default parameters were used according to the tutorial, appreciate it if you could look into the issue and help out on this.

C:\Users\meipaopao\StackNet\models\n6ut4jf5f4n3e5hjdl51n1p0ji0.pred (The system cannot find the file specified)
Exception in thread "Thread-46536" java.lang.NegativeArraySizeException
        at io.input.Retrievecolumn(input.java:1455)
        at ml.xgboost.XgboostRegressor.predict2d(XgboostRegressor.java:638)
        at ml.Bagging.scoringhelperbagv2.score(scoringhelperbagv2.java:158)
        at ml.Bagging.scoringhelperbagv2.run(scoringhelperbagv2.java:185)
        at java.lang.Thread.run(Unknown Source)
C:\Users\meipaopao\StackNet\models\doh9b4mmpej0cem7eik7q170h20.pred (The system cannot find the file specified)
Exception in thread "Thread-46537" java.lang.NegativeArraySizeException
        at io.input.Retrievecolumn(input.java:1455)
        at ml.xgboost.XgboostRegressor.predict2d(XgboostRegressor.java:638)
        at ml.Bagging.scoringhelperbagv2.score(scoringhelperbagv2.java:158)
        at ml.Bagging.scoringhelperbagv2.run(scoringhelperbagv2.java:185)
        at java.lang.Thread.run(Unknown Source)

Thank you  very much!
Andy

**Comment by kaz-Anova** [comment]
1. Can you try putting `verbose:true` for the xgboostregression to see if there is any other error?

2. Have a look [here,](https://github.com/kaz-Anova/StackNet/issues/26) maybe that fix for lightgbm, solves your broblems too if you apply it in XGBoost too.
