### ISSUE TITLE
Fail to train a regression task?

### ISSUE THREAD

**Issue by gdragone1** [kaz-Anova/StackNet#75]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: exceptions.IllegalStateException: The last layer of StackNet cannot have a classifier
        at ml.stacknet.StackNetRegressor.fit(StackNetRegressor.java:2532)
        at stacknetrun.runstacknet.main(runstacknet.java:556)
        ... 5 more

**Comment by goldentom42** [comment]
Hi @gdragone1, I think the error message says it all.

> The last layer of StackNet cannot have a classifier

Could you please tell us what the stack param file looks like ?

Thanks

**Comment by gdragone1** [comment]
Param file like this：
RandomForestRegression estimators:100 threads:1 rounding:3 cut_off_subsample:0.15 max_depth:7 max_features:0.7 min_leaf:3.0 min_split:5.0 Objective:ENTROPY row_subsample:0.95 seed:1 verbose:false

GradientBoostingForestRegression rounding:3 estimators:1000 shrinkage:0.1 threads:1 offset:0.00001 max_depth:8 max_features:0.4 min_leaf:4.0 min_split:8.0 Objective:RMSE row_subsample:0.7 seed:1 verbose:false

**Comment by goldentom42** [comment]
And this param file gives you the error you report ?

That's pretty weird !

**Comment by gdragone1** [comment]
Sorry, I remembered it. I fix it already. 
It's 'RandomForestClassifier' before. Thank you!






在 2019-03-02 19:10:43，"Olivier" <notifications@github.com> 写道：


And this param file gives you the error you report ?

That's pretty weird !

**Comment by goldentom42** [comment]
Ok thanks :)

Can you please mark as closed ?

cheers
